### ISSUE TITLE
MySQL 사용 배포 시 포함하지 않아야 할 파일이 궁금합니다.

### ISSUE THREAD

**Issue by verdantjuly** [verdantjuly/hwlv3#1]
<img width="645" alt="스크린샷 2023-06-22 오후 1 09 02" src="https://github.com/verdantjuly/hwlv3/assets/131671804/0c017df3-5de6-421a-a33a-e4aebb148063">

왼쪽은 VScode에서의 제 프로젝트이고 오른쪽은 .gitignore의 파일입니다.

**Comment by verdantjuly** [comment]
https://www.toptal.com/developers/gitignore 페이지에 SQL MySQL Sequelize를 검색해도 나오지 않아 질문드립니다~!

**Comment by verdantjuly** [comment]
각 파일의 삭제 이유!

/node_modules :  새 환경에서 설치하면 자동 생성 됨. 필요 없다!
package-lock.json : package 설치 및 변경 정보들이 담겨져 있음. 필요 없다!
/migrations : 데이터베이스 생성 기록인 것 같다. 필요 없을 것 같다. 
/config : 내 데이터베이스의 중요 정보 (암호 등)을 담고 있다. 들어가면 안 될 것 같다. 
/seeders : ? 빈 파일이라... 일단 지웠다.
.DS_Store : 구글링 : Mac의 정보를 담고 있다. 들어가면 안 될 것 같다.

**Comment by june2** [comment]
- package-lock.json : 모듈 버전 설치 정보들이 담겨져 있어 필요합니다. 협업시 다른 버전을 설치했을때 오류발생위험이 있기때문입니다. 
- /migrations : 협업할시, 기록을 남겨둬야 충돌이 안나기때문에 필요합니다.
- /config : secret 정보는 푸쉬 안하는게 맞습니다. 하지만 어떤 정보가 필요한지는 알아야하기에 secret정보를 제거하고 푸쉬합니다. 
- /seeders : seeders는 디폴트로 데이터를 만드는 역활을 합니다.

**Comment by verdantjuly** [comment]
감사합니다! 기억하고 다음에 MySQL을 사용할 경우 적용하겠습니다.
