### ISSUE TITLE
게시글을 전체 조회했을 때 데이터가 없어도 HTTP 200을 Response 해도 되나요?

### ISSUE THREAD

**Issue by verdantjuly** [verdantjuly/hwlv3#2]
https://github.com/verdantjuly/hwlv3/blob/4368092dbd7eaffac7152271b4b61f60c04840a3/routes/posts.route.js#L10-L23

**Comment by verdantjuly** [comment]
현재 상황 : DB 에 데이터가 없음
전체 조회시 length가 없으므로 false! 
```
return res.status(200).json({
            "message": "작성된 게시글이 없습니다. 첫 작성자가 되어 주세요!"
        }) 
```
를 응답함

**Comment by june2** [comment]
전체조회시, GET api/posts 게시글이 없을때 빈 array를 return 해야하므로 200으로 응답을 해주는게 맞습니다. 
 빈 array로 리턴하고 프론트에서 array 길이 체크해서 하시려는 메시지 표시를 하면됩니다.!

**Comment by verdantjuly** [comment]
감사합니다! 그렇게 진행하도록 하겠습니다~
