### ISSUE TITLE
유효성체크 관련

### ISSUE THREAD

**Issue by june2** [verdantjuly/hwlv3#6]
https://github.com/verdantjuly/hwlv3/blob/8c273e799aa19f7d9b758657cf879a5cc8c3bedf/routes/users.route.js#L16-L33

db를 조회하기전에 요청파라미터 유효성을 검증을 해야 해요
db 커넥션은 리소스를 많이 사용하기에 유효성을 미리 체크하면 성능에 이점을 가질수 있습니다.

**Comment by verdantjuly** [comment]
오.... 생각하지 못하였던 부분입니다! 감사합니다~
