### ISSUE TITLE
종합리뷰

### ISSUE THREAD

**Issue by june2** [verdantjuly/hwlv3#7]
- 코드 완성이 다 되지 않았네요.  모델에 필드 선언이 안되어 있습니다.
- 커밋로그 잘남겨주셨어요. 로그메시지도 상세히 남기면 좋을거같아요.
- readme 파일도 작성을 잘 해주셨네요.

**Comment by verdantjuly** [comment]
과제 제출 당시에는 모델과 마이그레이션을 일치 시키고 필드 선언을 하는 부분을 몰랐는데 팀 프로젝트를 진행하며 그 부분을 놓쳤던 걸 확인하고 배웠습니다. 로그 메시지도 다음부터는 상세히 남겨보도록 하겠습니다...! 진행하다보며 마음이 급하다 보니 git commit -m "메시지" 이렇게 적느라 다 제목밖에 없네요 ㅠ ㅠ ㅎㅎ 정성 담긴 좋은 리뷰 감사드립니다!
